### ISSUE TITLE
Readme contains instructions to curl | bash

### ISSUE THREAD

**Issue by Tea23** [bashlets/bashlets#1]
`curl | bash` is a dumb silly awful thing to do. You are asking your shell to run whatever script is contained at the source URL. I shouldn't have to explain why this is a fairly large security risk. Possible attack vectors include server side compromises, client side DNS redirection (malicious entries in `/etc/hosts` etc) and MITMs.

Viewing https://bashlets.github.io/ in a browser the whole thing is 'minified' or whatever so it's hard to read to ensure it's not running anything malicious.

Please change the instructions to something like:
```
wget bashlets.github.io/install.sh
chmod +x install.sh
./install.sh
```
Never ever ever ever ever ever ever ever ever ask someone to `curl | bash`.

See also https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

Love and hugs.

**Comment by realeroberto** [comment]
Changed to a git-based install process.
