### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dserodio** [bashlets/bashlets#4]
I followed the installation instructions and apparently it didn't work. No error messages are shown:

    $ git clone https://github.com/bashlets/bashlets.git
...

    $ cd bashlets
    $ make install
    bin/bashlets-install
    $ source bashlet library/interact
    bash: bashlet: No such file or directory

**Comment by realeroberto** [comment]
Closed by 27a81a440f85e1882f46b073a9ffbeac2e799a40
